# Generated by Django 5.1.3 on 2024-11-24 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('surprised', 'surprised'), ('loving', 'loving'), ('sleepy', 'sleepy'), ('nervous', 'nervous'), ('pensive', 'pensive'), ('relieved', 'relieved'), ('joyful', 'joyful')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(default='Unknown', max_length=100)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='MyMoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodhistories', to=settings.AUTH_USER_MODEL)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
    ]
