# Generated by Django 5.1.3 on 2024-11-22 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('happy', 'happy'), ('sad', 'sad'), ('surprised', 'surprised'), ('loving', 'loving'), ('sleepy', 'sleepy'), ('nervous', 'nervous'), ('pensive', 'pensive'), ('relieved', 'relieved'), ('joyful', 'joyful')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('api_source', models.CharField(max_length=100)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('api_source', models.CharField(max_length=100)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('api_source', models.CharField(max_length=100)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='MyMoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo_calendar.emotion')),
            ],
        ),
    ]
