# Generated by Django 5.1.3 on 2024-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emo_calendar', '0002_alter_mymoodhistory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='api_source',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
